@rtk = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJFbWFpbCI6ImFyY2hyYXBockBnbWFpbC5jb20iLCJVc2VySWQiOiIzNmIxOGRiMS0wMGEwLTQyNWUtODI1NC04OTE2MzhkZGU3MTgiLCJpYXQiOjE2ODc0NzkxMzd9.pBCLVGFfx1d6R__LBtOndrX6H9ExclypzrVDD1URwRY"
##@rtk1 = {{rtk}}
@atk = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJFbWFpbCI6Im5pZmVtaW9qaW5uaTIyQGdtYWlsLmNvbSIsIlVzZXJJZCI6IjA0ODRlMzljLWU4NDAtNDA5Zi1iMTEzLTYxODZhYTg2ZWExNiIsImlhdCI6MTY5Mjc4NTg0OSwiZXhwIjoxNjkyNzg5NDQ5fQ.D1eLoadl4pAMR92rMDRIcOgMxcihojy2QeCj1IrlONM
###@atk1 = {{atk}}
# @url = http://54.211.76.116
# @url = http://192.168.186.240
@url = http://127.0.0.1:3000

###
# GET {{url}}/DbOps/createdb?dbName=student
###
#GET {{url}}/DbOps/createtable
###

POST {{url}}/Student/SignUp
Content-Type: application/json

{
    "FirstName": "Nifemi",
    "LastName": "Ojinni",
    "Email": "nifemiojinni22@gmail.com",
    "Password": "@$Nifemi567",
    "IsVerifiedEmail": false,
    "University": "Elizade University",
    "UserName": ""
}

# POST {{url}}/Student/SignUp
# Content-Type: application/json

# {
#     "FirstName": "Raphael",
#     "LastName": "Olaiyapo",
#     "Email": "raphael.tunji@yahoo.com",
#     "Password": "Alade1&&&",
#     "IsVerifiedEmail": false,
#     "University": "Elizade University",
#     "UserName": ""
# }


###

###

POST {{url}}/Student/SignIn
Content-Type: application/json

{
    "UserName": "Nifemi.Ojinni",
    "Password": "@$Nifemi567"
}

###

###

PUT {{url}}/Student/VerifyEmail
Content-Type: application/json

{
   "EmailOTP": "018810",
   "Email": "nifemiojinni22@gmail.com"
}

###



POST {{url}}/Student/ForgotPassword?email=nifemiojinni22@gmail.com
###

###

PUT {{url}}/Student/ResetPassword
Content-Type: application/json

{
  "Email": "nifemiojinni22@gmail.com",
  "OTP": "815730",
  "NewPassword": "@$Nifemi567"
}

###

###

POST {{url}}/Student/SaveOrders?Email=nifemiojinni22@gmail.com
Authorization: BEARER {{atk}}
Content-Type: application/json

{
  "KitchenId": "8fea4167-d8fc-4355-ac0c-126512eec58a",
  "UserId": "48a4d227-e28a-4dab-9f35-1f25a6778bf1",
  "Description": "Mix egusi and okro soup together",
  "Items": [
    {
      "Name": "Amala",
      "Price": 800,
      "Scoops": 2
    },
    {
      "Name": "Egusi soup",
      "Price": 600,
      "Scoops": 2
    },
    {
      "Name": "Chicken",
      "Price": 1200,
      "Scoops": 1
    },
    {
      "Name": "Okro soup",
      "Price": 300,
      "Scoops": 1
    }
  ]
}


###   [
#               {
#                 "Name": "Fried rice",
#                 "Price": 500,
#                 "Scoops": 2
#               },
#               {
#                 "Name": "Jollof rice",
#                 "Price": 700,
#                 "Scoops": 2
#               },
#               {
#                 "Name": "Chicken",
#                 "Price": 1200,
#                 "Scoops": 2
#               },
#               {
#                 "Name": "Coke",
#                 "Price": 300,
#                 "Scoops": 2
#               },
#               {
#                 "Name": "Burger",
#                 "Price": 1200,
#                 "Scoops": 2
#               },
#           ]
# }


###

###

POST {{url}}/Kitchen/Create
Content-Type: application/json

{
  "Name": "RaphaelFood",
  "KitchenEmail": "support@raphaelfood.com",
  "KitchenPassword": "Alade1&&&",
  "Manager": "George Phillip",
  "ManagerPhone": 23481035635487,
  "AdminEmail": "Christi@gmail.com",
  "AdminPassword": "Christi@567",
  "University": "Elizade University, Ondo",
  "AccountNumber": 1234567890,
  "AccountName": "Raphael Food LTD",
  "BankName": "CitiBank PLC"
}

###

###

POST {{url}}/Kitchen/SignIn
Content-Type: application/json

{
  "Email": "support@raphaelfood.com",
  "Password": "Alade1&&&",
  "IsAdmin": false
}

###

###

PUT {{url}}/Kitchen/Update?email=support@raphaelfood.com
Content-Type: application/json

{
  "ManagerPhone": 61982374629
}
###

###

DELETE {{url}}/Kitchen/Delete?email=support@raphaelfood.com
###

###

POST {{url}}/Kitchen/CreateMenu
Content-Type: application/json

{
  "KitchenId": "3fb940c6-1047-4085-9aad-9ffc2593d184",
  "FoodName": "Ofada",
  "Category": "Food",
  "Class": "Rice",
  "Price": 1200,
  "Status": "available"
}

###

###

PUT {{url}}/Kitchen/UpdateMenu?MenuId=9e9bb2c5-ee50-4e12-8dba-100d488ad25f
Content-Type: application/json

{
  "Price": 850
}
###

###

DELETE {{url}}/Kitchen/DeleteMenu?MenuId=9e9bb2c5-ee50-4e12-8dba-100d488ad25f

###

GET {{url}}/Kitchen/GetKitchenMenus?KitchenId=8fea4167-d8fc-4355-ac0c-126512eec58a

####

POST {{url}}/Payment/MakePayment?Email=nifemiojinni22@gmail.com
Content-Type: application/json

{
  "orderId": "522a18a5-1033-40b4-9a23-bfc0fa4df3b0",
  "email": "nifemiojinni22@gmail.com",
  "amount": 120000
}

####

####

GET {{url}}/Payment/VerifyPayment?Reference=IjIcH04
#1v3ki9pgtp
#####


GET {{url}}/Kitchen/Fetch?food=rice

###