@rtk = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJFbWFpbCI6ImFyY2hyYXBockBnbWFpbC5jb20iLCJVc2VySWQiOiIzNmIxOGRiMS0wMGEwLTQyNWUtODI1NC04OTE2MzhkZGU3MTgiLCJpYXQiOjE2ODc0NzkxMzd9.pBCLVGFfx1d6R__LBtOndrX6H9ExclypzrVDD1URwRY"
##@rtk1 = {{rtk}}
@atk = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJFbWFpbCI6InJhcGhhZWwudHVuamlAeWFob28uY29tIiwiVXNlcklkIjoiOTIwOWI3NjktYThmNC00MmI1LWEzOTctODU1MjcyMDA3OWQ3IiwiaWF0IjoxNjk0MzQ1NjAyLCJleHAiOjE2OTQzNDkyMDJ9.mFbSh7iGvWw84xOYgFSIgW7cNdlTGPft__ip7dnqqW8
###@atk1 = {{atk}}
# @url = http://52.14.36.26:85
# @url = http://192.168.186.240
@url = http://127.0.0.1:3000

###
# GET {{url}}/DbOps/createdb?dbName=student
###
#GET {{url}}/DbOps/createtable
###

POST {{url}}/Student/SignUp
Content-Type: application/json

{
    "FirstName": "Alade",
    "LastName": "Aduragbemi",
    "Email": "raphael.tunji@yahoo.com",
    "Password": "Alade1&&&",
    "University": "Elizade University"
}
###

POST {{url}}/Student/SignIn
Content-Type: application/json

{
    "UserName": "Alade.Aduragbemi",
    "Password": "Aduragbemi1&&&"
}

###

POST {{url}}/Student/GetKitchensInUserUniversity
Authorization: Bearer {{atk}}
Content-Type: application/json

{
  "Email": "raphael.tunji@yahoo.com",
  "University": "Elizade University, Ondo"
}
###

PUT {{url}}/Student/VerifyEmail
Content-Type: application/json

{
   "EmailOTP": "625413",
   "Email": "raphael.tunji@yahoo.com"
}

###

POST {{url}}/Student/ForgotPassword?Email=raphael.tunji@yahoo.com
###

PUT {{url}}/Student/ResetPassword
Content-Type: application/json

{
  "Email": "raphael.tunji@yahoo.com",
  "OTP": "230568",
  "NewPassword": "Aduragbemi1&&&"
}
###

GET {{url}}/Student/ResendVerifyEmail?Email=raphael.tunji@yahoo.com

###

POST {{url}}/Student/SaveOrders?Email=raphael.tunji@yahoo.com
Authorization: BEARER {{atk}}
Content-Type: application/json

{
  "KitchenId": "1fc23982-7fc8-4628-bbbb-127708d4c95e",
  "Description": "Mix the rice",
  "Items": [
    {
      "Name": "Jollof",
      "Price": 58500,
      "Scoops": 195
    },
    {
      "Name": "Fried",
      "Price": 600,
      "Scoops": 2
    },
    {
      "Name": "Chicken",
      "Price": 1200,
      "Scoops": 1
    },
    {
      "Name": "Coke",
      "Price": 300,
      "Scoops": 1
    }
  ]
}
###

POST {{url}}/Student/WriteReview
Authorization: Bearer {{atk}}
Content-Type: application/json

{
  "KitchenId":"1fc23982-7fc8-4628-bbbb-127708d4c95e",
  "UserId":"67338fe9-5d3a-468e-be81-57b52ec7496b",
  "Reviewer":"Raphael Olaiyapo",
  "Review":"Laughter kitchen is the best"
}

###

DELETE {{url}}/Student/DeleteReviewById?ReviewId=f63fd2a8-f685-4356-ad3a-63199666f98c
Authorization: Bearer {{atk}}

###

PUT {{url}}/Student/UpdateReview
Authorization: Bearer {{atk}}
Content-Type: application/json

{
  "Id":"f63fd2a8-f685-4356-ad3a-63199666f98c",
  "UserId":"67338fe9-5d3a-468e-be81-57b52ec7496b",
  "Review":"Laughter kitchen is the best in this university",
  "WhoLiked":["swift@gmail.com","trending@yahoo.com"],
  "WhoDisliked":["trend@yahoo.com"]
}

###

POST {{url}}/Student/RegisterDeviceToken
Content-Type: application/json

{
  "FcmToken": "646fshfAzxQ9",
  "UserId": "67338fe9-5d3a-468e-be81-57b52ec7496b"
}

###

GET {{url}}/Student/GetOrdersByUserEmail?Email=raphael.tunji@yahoo.com
Authorization: Bearer {{atk}}

###

POST {{url}}/Student/FundWallet
Authorization: Bearer {{atk}}
Content-Type: application/json

{
  "email": "raphael.tunji@yahoo.com",
  "amount": 100000
}

###

POST {{url}}/Student/ChargeWallet
Authorization: Bearer {{atk}}
Content-Type: application/json

{
  "email": "raphael.tunji@yahoo.com",
  "orderId": "995d4456-dc6b-4aab-aac9-3d9c8ad1464e"
}

###

POST {{url}}/Student/SaveQuickOrders?Email=raphael.tunji@yahoo.com
Authorization: Bearer {{atk}}
Content-Type: application/json

{
  "KitchenId": "1fc23982-7fc8-4628-bbbb-127708d4c95e",
  "OrderName":"Afternoon Food",
  "Description": "Separate the chicken",
  "Items": [
    {
      "Name": "Jollof rice",
      "Price": 600,
      "Scoops": 2
    },
    {
      "Name": "Fried rice",
      "Price": 600,
      "Scoops": 2
    },
    {
      "Name": "Chicken",
      "Price": 1200,
      "Scoops": 1
    },
    {
      "Name": "Coke",
      "Price": 300,
      "Scoops": 1
    }
  ]
}

###

GET {{url}}/Student/GetQuickOrdersByUserEmail?Email=raphael.tunji@yahoo.com
Authorization: Bearer {{atk}}
###

PUT {{url}}/Student/UpdateQuickOrders?Email=raphael.tunji@yahoo.com
Authorization: Bearer {{atk}}
Content-Type: application/json

{
  "KitchenId": "1fc23982-7fc8-4628-bbbb-127708d4c95e",
  "OrderId":"3bcae8eb-4948-40fb-b275-7c2a5a32196e",
  "OrderName":"Night food",
  "Description": "Mix the soup together",
  "Items": [
    {
      "Id":"9d818115-1529-4e38-b22e-b554e0e9e15b",
      "Name": "Amala",
      "Price": 900,
      "Scoops": 3
    },
    {
      "Id":"f1ccd540-f169-4d67-b9f1-98fa8226e2e7",
      "Name": "Egusi soup",
      "Price": 600,
      "Scoops": 2
    },
    {
      "Id":"601d086a-3cc0-46e4-9631-90229e71a43e",
      "Name": "Chicken",
      "Price": 1200,
      "Scoops": 1
    },
    {
      "Id":"ec4682e2-a44a-453d-bbfe-893fb0a508c7",
      "Name": "Okro soup",
      "Price": 300,
      "Scoops": 2
    }
  ]
}

###

DELETE {{url}}/Student/DeleteQuickOrders?QoId=3bcae8eb-4948-40fb-b275-7c2a5a32196e
Authorization: Bearer {{atk}}

###

POST {{url}}/Kitchen/Create
Content-Type: application/json

{
  "KitchenName": "Penuel",
  "KitchenEmail": "archraphr@gmail.com",
  "ManagerFirstName": "Tim",
  "ManagerLastName": "Cylon",
  "ManagerPhone": 2348102242355,
  "ManagerEmail": "archraphr@gmail.com",
  "Password": "Aduragbemi1&&&",
  "University": "Elizade University, Ondo",
  "AccountNumber": 3045313300,
  "AccountName": "Penuel LTD",
  "BankCode": "011",
  "BankName": "CitiBank PLC"
}

###

POST {{url}}/Kitchen/SignIn
Content-Type: application/json

{
  "Email": "aladeraphredo@yahoo.com",
  //"Email":"raphael.tunji@yahoo.com",  
  "Password": "Aduragbemi1&&&"
}

###

PUT {{url}}/Kitchen/VerifyEmail
Content-Type: application/json

{
  "EmailOTP": "924755",
  "Email":"raphael.tunji@yahoo.com"
  //"Email": "aladeraphredo@yahoo.com"
}


###

GET {{url}}/Kitchen/ResendVerifyEmail?Email=aladeraphredo@yahoo.com

###

POST {{url}}/Kitchen/ForgotPassword?Email=aladeraphredo@yahoo.com
###

PUT {{url}}/Kitchen/ResetPassword
Content-Type: application/json

{
  "Email":"aladeraphredo@yahoo.com",
  "OTP": "077713",
  "NewPassword": "Aduragbemi1&&&"
}

###

PUT {{url}}/Kitchen/Update?Email=aladeraphredo@yahoo.com
Authorization: Bearer {{atk}}
Content-Type: application/json

{
  //"AccountNumber":363846484649,
  "ManagerPhone": 61982374629
}
###

DELETE {{url}}/Kitchen/Delete?Email=raphael.tunji@yahoo.com
###

POST {{url}}/Kitchen/AddStaff
Authorization: Bearer {{atk}}
Content-Type: application/json

{
  "KitchenId": "1fc23982-7fc8-4628-bbbb-127708d4c95e",
  "FirstName": "Raphael",
  "LastName": "Olaiyapo",
  "Email": "raphael.tunji@yahoo.com",
  "Password": "Alade1&&&",
  "Phone": 2348102242355,
  "University": "Elizade University",
  "Role": "basic"
}

###

PUT {{url}}/Kitchen/UpdateStaff?Email=raphael.tunji@yahoo.com
Authorization: Bearer {{atk}}
Content-Type: application/json

{
  "FirstName": "Gorge",
  "LastName": "Alade"
}

###

DELETE {{url}}/Kitchen/DeleteStaff?Email=raphael.tunji@yahoo.com
Authorization: Bearer {{atk}}

###

POST {{url}}/Kitchen/CreateMenu
Authorization: Bearer {{atk}}
Content-Type: application/json

{
  "KitchenId": "1fc23982-7fc8-4628-bbbb-127708d4c95e",
  "FoodName": "Coke",
  "Category": "Drinks",
  "Class": "Mineral",
  "Price": 300,
  "TotalQuantity": 200,
  "Status": "available"
}

###

PUT {{url}}/Kitchen/UpdateMenu?MenuId=56481cf3-bf86-4991-b39f-beb8fe064d27
Authorization: Bearer {{atk}}
Content-Type: application/json

{
  "TotalQuantity": 200,
  "Status": "available"
}
###

DELETE {{url}}/Kitchen/DeleteMenu?MenuId=9d6ea044-1c3e-4032-8b82-573df5dd5fa8
Authorization: Bearer {{atk}}
###

GET {{url}}/Kitchen/GetKitchenMenus?KitchenId=1fc23982-7fc8-4628-bbbb-127708d4c95e
Authorization: Bearer {{atk}}
###

GET {{url}}/Kitchen/GetKitchenOrders?Email=aladeraphredo@yahoo.com
Authorization: Bearer {{atk}}

###

GET {{url}}/Kitchen/GetBanks
Authorization: Bearer {{atk}}

###

GET {{url}}/Kitchen/ValidateKitchenBank?Email=aladeraphredo@yahoo.com
Content-Type: application/json

{
  "AccountNumber": "3045313300",
  "BankCode": "011",
  "ShouldProceed": true
}

###

GET {{url}}/Kitchen/GetReviewsByKitchenId?KitchenId=1fc23982-7fc8-4628-bbbb-127708d4c95e
Authorization: Bearer {{atk}}

###

POST {{url}}/Kitchen/SendNotification
Authorization: Bearer {{atk}}
Content-Type: application/json

{
  "KitchenId": "1fc23982-7fc8-4628-bbbb-127708d4c95e",
  "UserId": "67338fe9-5d3a-468e-be81-57b52ec7496b",
  "Title": "Order is ready",
  "Message": "Your Order is ready for collection" 
}

###

POST {{url}}/Kitchen/NotifiyAllUsers
Authorization: Bearer {{atk}}
Content-Type: application/json

{
  "KitchenId": "1fc23982-7fc8-4628-bbbb-127708d4c95e",
  "UserId": "bb98c2c8-60e1-45d8-9771-742c0d8cb03b",
  "Title": "Order is ready",
  "Message": "Your Order is ready for collection" 
}

###

POST {{url}}/Payment/MakePayment
Authorization: Bearer {{atk}}
Content-Type: application/json

{
  "orderId": "4701d0c1-27f9-41ec-b01d-8c7bd142ce5e",
  "email": "raphael.tunji@yahoo.com",
  "amount": 0
}

####

GET {{url}}/Payment/VerifyPayment?Reference=WRwdgDV
Authorization: Bearer {{atk}}
#1v3ki9pgtp
#####


# {
#   "status": true,
#   "message": "Transfer recipient created successfully",
#   "data": {
#     "active": true,
#     "createdAt": "2023-08-31T14:38:33.837Z",
#     "currency": "NGN",
#     "domain": "test",
#     "id": 59982562,
#     "integration": 962004,
#     "name": "OLAIYAPO RAPHAEL ADETUNJI",
#     "recipient_code": "RCP_xn5y7ll5vzh47ma",
#     "type": "nuban",
#     "updatedAt": "2023-08-31T14:38:33.837Z",
#     "is_deleted": false,
#     "isDeleted": false,
#     "details": {
#       "authorization_code": null,
#       "account_number": "3045313300",
#       "account_name": "OLAIYAPO RAPHAEL ADETUNJI",
#       "bank_code": "011",
#       "bank_name": "First Bank of Nigeria"
#     }
#   }
# }