@rtk = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJFbWFpbCI6ImFyY2hyYXBockBnbWFpbC5jb20iLCJVc2VySWQiOiIzNmIxOGRiMS0wMGEwLTQyNWUtODI1NC04OTE2MzhkZGU3MTgiLCJpYXQiOjE2ODc0NzkxMzd9.pBCLVGFfx1d6R__LBtOndrX6H9ExclypzrVDD1URwRY"
##@rtk1 = {{rtk}}
@atk = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJFbWFpbCI6InJhcGhhZWwudHVuamlAeWFob28uY29tIiwiVXNlcklkIjoiMjg2OGNmZmEtN2U0Ni00NzdhLTk3MjYtYmJlZGE0NjUwNTMwIiwiaWF0IjoxNjkzNTM1NDg4LCJleHAiOjE2OTM1MzkwODh9.jSQc11y0tJcfvyplaQysOKMa8p8euc9pXsYdgT51ds8
###@atk1 = {{atk}}
# @url = http://54.211.76.116
# @url = http://192.168.186.240
@url = http://127.0.0.1:3000

###
# GET {{url}}/DbOps/createdb?dbName=student
###
#GET {{url}}/DbOps/createtable
###

POST {{url}}/Student/SignUp
Content-Type: application/json

{
    "FirstName": "Nifemi",
    "LastName": "Ojinni",
    "Email": "nifemiojinni22@gmail.com",
    "Password": "@$Nifemi567",
    "IsVerifiedEmail": false,
    "University": "Elizade University",
    "UserName": ""
}

# POST {{url}}/Student/SignUp
# Content-Type: application/json

# {
#     "FirstName": "Raphael",
#     "LastName": "Olaiyapo",
#     "Email": "raphael.tunji@yahoo.com",
#     "Password": "Alade1&&&",
#     "IsVerifiedEmail": false,
#     "University": "Elizade University",
#     "UserName": ""
# }


###

###

POST {{url}}/Student/SignIn
Content-Type: application/json

{
    "UserName": "Raphael.Olaiyapo",
    "Password": "Aduragbemi1&&&"
}

###

PUT {{url}}/Student/VerifyEmail
Content-Type: application/json

{
   "EmailOTP": "018810",
   "Email": "nifemiojinni22@gmail.com"
}

###

POST {{url}}/Student/ForgotPassword?email=nifemiojinni22@gmail.com
###

###

PUT {{url}}/Student/ResetPassword
Content-Type: application/json

{
  "Email": "nifemiojinni22@gmail.com",
  "OTP": "815730",
  "NewPassword": "@$Nifemi567"
}

###

###

POST {{url}}/Student/SaveOrders?Email=raphael.tunji@yahoo.com
Authorization: BEARER {{atk}}
Content-Type: application/json

{
  "KitchenId": "238e4212-4f4f-4e3c-ad20-8512eb11c397",
  "Description": "Mix egusi and okro soup together",
  "Items": [
    {
      "Name": "Jollof rice",
      "Price": 300,
      "Scoops": 1
    },
    {
      "Name": "Fried rice",
      "Price": 300,
      "Scoops": 1
    },
    {
      "Name": "Chicken",
      "Price": 1200,
      "Scoops": 1
    },
    {
      "Name": "Coke",
      "Price": 500,
      "Scoops": 1
    }
  ]
}


###   [
#               {
#                 "Name": "Fried rice",
#                 "Price": 500,
#                 "Scoops": 2
#               },
#               {
#                 "Name": "Jollof rice",
#                 "Price": 700,
#                 "Scoops": 2
#               },
#               {
#                 "Name": "Chicken",
#                 "Price": 1200,
#                 "Scoops": 2
#               },
#               {
#                 "Name": "Coke",
#                 "Price": 300,
#                 "Scoops": 2
#               },
#               {
#                 "Name": "Burger",
#                 "Price": 1200,
#                 "Scoops": 2
#               },
#           ]
# }


###

###

POST {{url}}/Kitchen/Create
Content-Type: application/json

{
  "KitchenName": "RaphaelFood",
  "KitchenEmail": "raphael.tunji@yahoo.com",
  "ManagerFirstName": "George",
  "ManagerLastName": "George",
  "ManagerPhone": 23481035635487,
  "ManagerEmail": "raphael.tunji@yahoo.com",
  "Password": "Christi@567",
  "University": "Elizade University, Ondo",
  "AccountNumber": 3045313300,
  "AccountName": "Raphael Food LTD",
  "BankCode": "011",
  "BankName": "CitiBank PLC"
}

###

POST {{url}}/Kitchen/SignIn
Content-Type: application/json

{
  "Email": "nifemiojinni22@gmail.com",
  "Password": "Alade1&&&"
}

###

PUT {{url}}/Kitchen/VerifyEmail
Content-Type: application/json

{
  "EmailOTP": "498342",
  "Email": "nifemiojinni22@gmail.com"
}


###

GET {{url}}/Kitchen/ResendVerifyEmail?email=nifemiojinni22@gmail.com

###

###

PUT {{url}}/Kitchen/UpdateStaff?email=nifemiojinni22@gmail.com
Authorization: Bearer {{atk}}
Content-Type: application/json

{
  "Role": "admin"
}

###

PUT {{url}}/Kitchen/Update?email=raphael.tunji@yahoo.com
Authorization: Bearer {{atk}}
Content-Type: application/json

{
  "ManagerPhone": 61982374629
}
###

DELETE {{url}}/Kitchen/Delete?email=raphael.tunji@yahoo.com
###

###

DELETE {{url}}/Kitchen/DeleteStaff?email=raphael.tunji@yahoo.com

###

POST {{url}}/Kitchen/CreateMenu
Authorization: Bearer {{atk}}
Content-Type: application/json

{
  "KitchenId": "e4e73045-6827-488f-a833-a907bc5ea5f8",
  "FoodName": "Jollof",
  "Category": "Food",
  "Class": "Rice",
  "Price": 1200,
  "TotalQuantity": 200,
  "Status": "available"
}

###

PUT {{url}}/Kitchen/UpdateMenu?MenuId=a50cc3f8-b081-4536-a6bd-07e9e424f391
Authorization: Bearer {{atk}}
Content-Type: application/json

{
  "Price": 600
}
###

DELETE {{url}}/Kitchen/DeleteMenu?MenuId=9e9bb2c5-ee50-4e12-8dba-100d488ad25f
###
GET {{url}}/Kitchen/GetKitchenMenus?KitchenId=e4e73045-6827-488f-a833-a907bc5ea5f8
Authorization: Bearer {{atk}}
###

POST {{url}}/Payment/MakePayment?Email=nifemiojinni22@gmail.com
Authorization: Bearer {{atk}}
Content-Type: application/json

{
  "orderId": "cf66da8a-87ea-4730-8f13-3ed6d62519a8",
  "email": "nifemiojinni22@gmail.com",
  "amount": 0
}

####

GET {{url}}/Payment/VerifyPayment?Reference=WRwdgDV
Authorization: Bearer {{atk}}
#1v3ki9pgtp
#####

GET {{url}}/Kitchen/Fetch?food=rice

###

DELETE {{url}}/Kitchen/DeleteStaff?email=raphael.tunji@yahoo.com

###

PUT {{url}}/Kitchen/UpdateStaff?email=raphael.tunji@yahoo.com
Content-Type: application/json

{
  "FirstName": "Gorge",
  "LastName": "Alade"
}

###

GET {{url}}/Kitchen/GetKitchenOrders?Email=raphael.tunji@yahoo.com
Authorization: Bearer {{atk}}

###

GET {{url}}/Student/GetOrdersByUserEmail?Email=raphael.tunji@yahoo.com
Authorization: Bearer {{atk}}

###

GET {{url}}/Kitchen/GetBanks
Authorization: Bearer {{atk}}

###

GET {{url}}/Kitchen/ValidateKitchenBank?email=raphael.tunji@yahoo.com
Content-Type: application/json

{
  "AccountNumber": "3045313300",
  "BankCode": "011",
  "ShouldProceed": true
}

###


# {
#   "status": true,
#   "message": "Transfer recipient created successfully",
#   "data": {
#     "active": true,
#     "createdAt": "2023-08-31T14:38:33.837Z",
#     "currency": "NGN",
#     "domain": "test",
#     "id": 59982562,
#     "integration": 962004,
#     "name": "OLAIYAPO RAPHAEL ADETUNJI",
#     "recipient_code": "RCP_xn5y7ll5vzh47ma",
#     "type": "nuban",
#     "updatedAt": "2023-08-31T14:38:33.837Z",
#     "is_deleted": false,
#     "isDeleted": false,
#     "details": {
#       "authorization_code": null,
#       "account_number": "3045313300",
#       "account_name": "OLAIYAPO RAPHAEL ADETUNJI",
#       "bank_code": "011",
#       "bank_name": "First Bank of Nigeria"
#     }
#   }
# }